### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by mcmillhj** [leops/react-graph-editor#1]
Just wondering, are there examples of graphs that have been built using this library?

**Comment by leops** [comment]
I have two of them, which is the reason I made this into a library in the first place. The first one is [Focus](https://github.com/leops/focus), a viewer for the Source Engine's Hammer I/O system:

![focus.png](https://s3.eu-west-3.amazonaws.com/l3ops/focus.png)

The other one is the [Rasen Editor](https://github.com/leops/rasen-editor), an editor for SPIR-V shaders:

![rasen.png](https://s3.eu-west-3.amazonaws.com/l3ops/rasen.png)

**Comment by mcmillhj** [comment]
Thanks! I'll dig into the source of those.
